#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_replace --file="$install_dir/.env" \
    --match="APP_URL=https://$old_domain" \
    --replace="APP_URL=https://$new_domain"

pushd "$install_dir"
    ynh_exec_as_app "php$php_version" artisan config:clear -n
    ynh_exec_as_app "php$php_version" artisan config:cache -n
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
