#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================
ynh_script_progression --message="Checking version..."

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# If app_key doesn't exist, create it
if [ -z "$app_key" ]; then
	app_key="$(grep "^APP_KEY=" "$install_dir/.env" | cut -d= -f2)"
	ynh_app_setting_set --app=$app --key=app_key --value=$app_key
fi

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN COMPOSER BUILD...)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=7

	# Download, check integrity, uncompress and patch the source from app.src
	ynh_setup_source --dest_dir="$install_dir" --keep=".env storage/oauth-private.key storage/oauth-public.key storage/private_uploads public/uploads"
fi

chown -R $app:www-data "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Upgrading system configurations related to $app..." --weight=1

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=low --footprint=low

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# INSTALL AND INITIALIZE COMPOSER
#=================================================
ynh_script_progression --message="Installing Composer..." --weight=15

# Install composer
ynh_install_composer

ynh_exec_warn_less ynh_composer_exec --commands="dump-autoload"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression --message="Updating a configuration file..."

ynh_backup_if_checksum_is_different --file="$install_dir/.env"
# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum --file="$install_dir/.env"
# XXX: Regenerate .env instead ?
# ynh_add_config --template="../conf/.env" --destination="$install_dir/.env"

#=================================================
# BUILDING
#=================================================
ynh_script_progression --message="Building..."

pushd "$install_dir"
	php$phpversion artisan migrate -n --force
	php$phpversion artisan config:clear -n 
	php$phpversion artisan config:cache -n 
popd

# Set permissions on app files
chown -R $app:www-data $install_dir
chmod -R o-rwx $install_dir
chmod -R 755 $install_dir/storage
chmod -R 755 $install_dir/public/uploads

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed"
