#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# If app_key doesn't exist, create it
if [ -z "$app_key" ]; then
	app_key="$(grep "^APP_KEY=" "$install_dir/.env" | cut -d= -f2)"
	ynh_app_setting_set --key=app_key --value=$app_key
fi

if (( ${#language}  == 2 )); then
    # fr -> fr-FR
    language="${language}-${language^^}"
    ynh_app_setting_set --key="language" --value="$language"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir" --keep=".env storage/oauth-private.key storage/oauth-public.key storage/private_uploads public/uploads"

# setup page tries to access https://$domain$path/.env and fails on self signed certs
ynh_replace --file="$install_dir/app/Http/Controllers/SettingsController.php" \
	--match="->get(URL::to('.env'))" \
	--replace="->withoutVerifying()->get(URL::to('.env'))"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_backup_if_checksum_is_different "$install_dir/.env"

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "$install_dir/.env"
# XXX: Regenerate .env instead ?
# ynh_config_add --template="snipeit.env" --destination="$install_dir/.env"

#=================================================
# BUILDING
#=================================================
ynh_script_progression "Building $app..."

#REMOVEME? ynh_composer_install
ynh_composer_exec install --no-dev

ynh_composer_exec dump-autoload

pushd "$install_dir"
	ynh_exec_as_app "php$php_version" artisan migrate -n --force
	ynh_exec_as_app "php$php_version" artisan config:clear -n
	ynh_exec_as_app "php$php_version" artisan config:cache -n
popd

# Set permissions on app files
chmod -R 755 "$install_dir/storage"
chmod -R 755 "$install_dir/public/uploads"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
